#pragma once

#define MQTT_SERVER "<MQTT_SERVER_ADDRESS>"
#define MQTT_PORT   1883
#define MQTT_TOPIC  "<MQTT_TOPIC>"
#define MQTT_STATE  MQTT_TOPIC "/state/current"
#define MQTT_CHANGE MQTT_TOPIC "/state/change"
#define MQTT_SPEED  MQTT_TOPIC "/charge_speed"
#define MQTT_SET_PWM MQTT_TOPIC "/set_pwm"
#define MQTT_POWER MQTT_TOPIC "/power"
#define MQTT_ENERGY MQTT_TOPIC "/energy"
#define MQTT_CURRENT MQTT_TOPIC "/current"
#define MQTT_VOLTAGE MQTT_TOPIC "/voltage"
#define MQTT_FREQUENCY MQTT_TOPIC "/frequency"
#define MQTT_POWER_FACTOR MQTT_TOPIC "/power_factor"
#define MQTT_DEBUG MQTT_TOPIC "/debug"
#define MQTT_DEBUG_INIT MQTT_TOPIC "/debug/init"
#define MQTT_DEBUG_READ MQTT_TOPIC "/debug/read"
#define MQTT_DEBUG_COMM MQTT_TOPIC "/debug/comm"
#define MQTT_DEBUG_TIME MQTT_TOPIC "/debug/time"