[env:sonoff_mini_base]
platform = espressif8266
board = esp8285
framework = arduino
upload_speed = 115200
upload_resetmethod = nodemcu
monitor_speed = 9600
monitor_filters = colorize, time
upload_protocol = espota
upload_flags = --auth=
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.0
    mandulaj/PZEM-004T-v30@^1.1.2
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

; ── Device A: sonoff-mini-pzem-edf ────────────────────────────────────
; Default hostname: sonoff-mini-pzem-edf  PZEM address: 0x04
[env:sonoff_mini_edf]
extends = env:sonoff_mini_base
upload_port = 192.168.1.15
build_flags =
    ${env:sonoff_mini_base.build_flags}
    -DDEFAULT_HOSTNAME='"sonoff-mini-pzem-edf"'
    -DTOPIC_PUBLISH_POWER='"home/power/edf"'
    -DFORCE_DEBUG_DISABLED


; ── Device B: sonoff-mini-pzem-solarprod ─────────────────────────────────────
; Default hostname: sonoff-mini-pzem-solarprod  PZEM address: 0x02
[env:sonoff_mini_solarprod]
extends = env:sonoff_mini_base
upload_port = 192.168.1.41
build_flags =
    ${env:sonoff_mini_base.build_flags}
    -DDEFAULT_HOSTNAME='"sonoff-mini-pzem-solar"'
    -DTOPIC_PUBLISH_POWER='"home/power/solar"'
    -DFORCE_DEBUG_ENABLED
    -DFORCE_DEBUG_FLAGS=7

